{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "biel.name" . }}
  labels:
    {{- include "biel.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    {{- if .Values.statefulset.enabled }}  # 判断使用deployment和statefulset类型
    kind: StatefulSet 
    {{- else }}
    kind: Deployment
    {{- end }}
    name: {{ include "biel.name" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.averageUtilization }}
{{- end }}
