apiVersion: v1
kind: Service
metadata:
  name: {{ include "biel.name" . }}
  labels:
    {{- include "biel.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports: 
    {{- toYaml .Values.service.ports | nindent 4 }}
  selector:
    {{- include "biel.selectorLabels" . | nindent 4 }}