name: Deploy on server
on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run tests
        run: |
          cd /home/datalab/pyDemo
          git pull origin
          docker build -t pydocker .
          docker-compose up -d
          docker-compose down
    
