name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
    - name: Docker Login
      run: docker login -u airasuka -p ${{ secrets.DOCKER_HUB_PWD }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag airasuka/dockertest:pydocker-${{github.event.pull_request_review_comment}}
    - name: Push the Docker Image
      run: docker push airasuka/dockertest:pydocker
