name: Update Chart Version and Push Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update Chart Version
        run: |
          # 获取当前tag版本号
          current_version=$(grep 'tag:' chart/production/values.yaml | awk '{print $2}')
          
          # 提取版本号中的数字
          version_number=$(echo $current_version | awk -F 'release-' '{print $2}')
          
          # 将版本号加一
          new_version="release-0.0.$((version_number + 1))"
          # echo "current_version = ${{current_version}} ,new_version = ${{new_version}}"
          # 替换values.yaml文件中的tag版本号
          sed -i "s/tag: \"$current_version\"/tag: \"$new_version\"/g" chart/production/values.yaml

      - name: Build and Push Docker Image
        run: |
          # 登录到私人harbor仓库
          #echo "${{ secrets.HARBOR_PASSWORD }}" | docker login harbor.bielcrystal.com -u ${{ secrets.HARBOR_USERNAME }} --password-stdin
          
          # 构建镜像
          #docker build -t harbor.bielcrystal.com/library/pydocker:$new_version .
          
          # 推送镜像到私人harbor仓库
          #docker push harbor.bielcrystal.com/library/pydocker:$new_version
