name: Auto-increment tag on merge to master

on:
  push:
    branches:
      - master

jobs:
  auto_increment_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Increment tag in values.yaml
        run: |
          current_tag=$(grep 'tag:' chart/production/values.yaml | awk '{print $2}')
          major=$(echo $current_tag | cut -d- -f2 | cut -d. -f2)
          minor=$(echo $current_tag | cut -d. -f3)
          new_minor=$((minor+1))
          new_tag="release-0.${major}.${new_minor}"
          # sed -i "s/tag: \"$current_tag\"/tag: \"$new_tag\"/" chart/production/values.yaml
          echo "current_tag = $current_tag major = $major minor = $minor new_tag = $new_tag"
        env:
          NEW_TAG: $new_tag
      - name: Modify Chart Yaml Tag
        uses: mikefarah/yq@master
        with:
          cmd: |
            files=$(find . -type f -name "values.yaml")
            for f in $files; do yq eval -i '.image.tag="$NEW_TAG"' $f; done
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          author_email: datalab@bielcrystal.com
          message: "Update image tag to $NEW_TAG"
          add: "*.yaml"

      - name: Login to Harbor registry
        run: docker login harbor.bielcrystal.com -u ${{ secrets.HARBOR_USERNAME }} -p ${{ secrets.HARBOR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t harbor.bielcrystal.com/library/pydocker:$new_tag .
          docker push harbor.bielcrystal.com/library/pydocker:$new_tag
