name: Auto-increment tag on merge to master

on:
  push:
    branches:
      - master

jobs:
  auto_increment_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Increment tag in values.yaml
        run: |
          current_tag=$(grep 'tag:' chart/production/values.yaml | awk '{print $2}')
          major=$(echo $current_tag | cut -d. -f1 | cut -d- -f2)
          minor=$(echo $current_tag | cut -d. -f2)
          new_minor=$((minor+1))
          new_tag="release-0.${major}.${new_minor}"
          sed -i "s/tag: \"$current_tag\"/tag: \"$new_tag\"/" chart/production/values.yaml
          echo "new_tag = ${{new_tag}}"

      - name: Commit and push updated values.yaml
        run: |
          git config --global user.email "WQ@example.com"
          git config --global user.name "WQ"
          git add chart/production/values.yaml
          git commit -m "Auto-increment tag to $new_tag"
          git push

      - name: Login to Harbor registry
        run: docker login harbor.bielcrystal.com -u ${{ secrets.HARBOR_USERNAME }} -p ${{ secrets.HARBOR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t harbor.bielcrystal.com/library/pydocker:$new_tag .
          docker push harbor.bielcrystal.com/library/pydocker:$new_tag
