name: Release Workflow

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get current tag
        id: get_tag
        run: echo ::set-output name=tag::$(grep 'tag:' chart/production/values.yaml | awk '{print $2}')

      - name: Calculate new tag
        id: calculate_tag
        run: |
          current_tag=${{ steps.get_tag.outputs.tag }}
          major=$(echo $current_tag | cut -d. -f1 | cut -d- -f2)
          minor=$(echo $current_tag | cut -d. -f2)
          new_minor=$((minor+1))
          new_tag="release-0.${major}.${new_minor}"
          echo ::set-output name=new_tag::$new_tag

      - name: Update values.yaml
        run: yq eval -i '.tag = env(new_tag)' chart/production/values.yaml

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add chart/production/values.yaml
          git commit -m "Bump version to ${{ steps.calculate_tag.outputs.new_tag }}"
          git push

      - name: Docker login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login harbor.bielcrystal.com -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t harbor.bielcrystal.com/library/pydocker:${{ steps.calculate_tag.outputs.new_tag }} .
          docker push harbor.bielcrystal.com/library/pydocker:${{ steps.calculate_tag.outputs.new_tag }}
