name: Update Image Tag and Push to Harbor

on:
  push:
    branches:
      - master

jobs:
  update-tag-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get the current tag from values.yaml
        id: get-tag
        run: echo ::set-output name=tag::$(awk '/tag:/ {print $2}' chart/production/values.yaml)

      - name: Increment the tag
        id: increment-tag
        run: echo ::set-output name=tag::v$(echo "${{ steps.get-tag.outputs.tag }}" | cut -c2- | awk -F. '{$NF+=1; OFS="."; print $0}')

      - name: Update values.yaml with the new tag
        run: sed -i "s/tag: \"${{ steps.get-tag.outputs.tag }}\"/tag: \"${{ steps.increment-tag.outputs.tag }}\"/" chart/production/values.yaml

      - name: Commit the changes
        run: |
          git add chart/production/values.yaml
          git commit -m "Increment image tag"
          git push

      - name: Build and push Docker image
        run: |
          docker build -t harbor.bielcrystal.com/library/pydocker:${{ steps.increment-tag.outputs.tag }} .
          echo "${{ secrets.HARBOR_PASSWORD }}" | docker login harbor.bielcrystal.com -u ${{ secrets.HARBOR_USERNAME }} --password-stdin
          docker push harbor.bielcrystal.com/library/pydocker:${{ steps.increment-tag.outputs.tag }}
