name: Increase Version and Push Image Tag

on:
  push:
    branches:
      - main

jobs:
  increase-version-and-push-image-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Increase version in values.yaml
        run: |
          sed -i 's/tag: "v0.2"/tag: "v0.$(( $(echo "$(cat chart/production/values.yaml)" | grep -oP '(?<=tag: "v)0*\K[0-9]+') + 1 ))"/' chart/production/values.yaml
          git add chart/production/values.yaml
          git commit -m "Bump version in values.yaml"
          git push

      - name: Login to Harbor registry
        run: echo "${{ secrets.HARBOR_PASSWORD }}" | docker login harbor.bielcrystal.com -u ${{ secrets.HARBOR_USERNAME }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t harbor.bielcrystal.com/library/pydocker:latest .
          

      - name: Create and push new tag
        run: |
          docker tag harbor.bielcrystal.com/library/pydocker:latest harbor.bielcrystal.com/library/pydocker:v0.$(( $(echo "$(cat chart/production/values.yaml)" | grep -oP '(?<=tag: "v)0*\K[0-9]+') ))
          docker push harbor.bielcrystal.com/library/pydocker:v0.$(( $(echo "$(cat chart/production/values.yaml)" | grep -oP '(?<=tag: "v)0*\K[0-9]+') ))
