name: Update Chart Values and Push Image

on:
  push:
    branches:
      - master

jobs:
  update-chart-values-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update Chart Values
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'chart/production/values.yaml'
          propertyPath: 'image.tag'
          value: ${{ steps.increment-tag.outputs.newTag }}
          commitChange: true
          message: 'Update image tag in values.yaml'

      - name: Increment Tag
        id: increment-tag
        run: |
          currentTag=$(awk '/tag:/ {print $2}' chart/production/values.yaml | tr -d '"')
          IFS='.' read -r major minor <<< $currentTag
          newTag="release-$major.$((minor + 1))"
          echo "::set-output name=newTag::$newTag"

      - name: Login to Harbor Registry
        run: echo "${{ secrets.HARBOR_TOKEN }}" | docker login harbor.bielcrystal.com -u ${{ secrets.HARBOR_USERNAME }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t harbor.bielcrystal.com/library/pydocker:latest .
          docker push harbor.bielcrystal.com/library/pydocker:latest
