name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
    - name: Get a review comment
      id: PRcoment
      uses: actions/github-script@v4
      with:
        script: |
          const pr_number = context.payload.pull_request.number;
          console.log(pr_number);
    - name: Docker Login
      run: docker login -u airasuka -p ${{ secrets.DOCKER_HUB_PWD }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag airasuka/dockertest:pydocker${{ steps.PRcomment.outputs.pr_number }}
    - name: Push the Docker Image
      run: docker push airasuka/dockertest:pydocker${{ steps.PRcomment.outputs.pr_number }}
