name: Docker Image CI

on:
  pull_request_review:
     types:
       - submitted
       - edited
 
jobs:

  build:
    if: ${{ github.event.review.state == 'approved' && contains(github.event.review.body, 'release-') && github.event.pull_request.base.ref == 'master' }}   
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: airasuka
          password: ${{ secrets.DOCKER_HUB_PWD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          tags: airasuka/pydocker:${{ github.event.review.body }}

