name: Docker Image CI

on:
  pull_request_review:
     types:
       - submitted
       - edited
 
jobs:

  build:
    if: ${{ github.event.review.state == 'approved' && contains(github.event.review.body, 'release-') && github.event.pull_request.base.ref == 'master' }}   
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: airasuka
        password: ${{ secrets.DOCKER_HUB_PWD }}
    - uses: docker/build-push-action@v4.1.1
      with:
        push: true
        file: ./Dockerfile
        tags: airasuka/pydocker:${{ github.event.review.body }}


