name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Get PR Comment
        id: pr_comment
        uses: actions/github-script@v4
        with:
          script: |
            const pr_number = context.payload.pull_request.number;
            console.log(pr_number);
