name: Docker Image CI

on:
  - pull_request_review
 
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
    - name: Check print github.event.pull_request.title
      run: echo "${{ github.event.pull_request.title }}"
    - name: Check print github.event.pull_request.body
      run: echo "${{ github.event.pull_request.body }}"
    - name: Check print github.event.comment.body
      run: echo "${{ github.event.comment.body }}"
    - name: Check print github.event.review.body
      run: echo "${{ github.event.review.body }}"
    - name: Check print github.event.review_comment.body
      run: echo "${{ github.event.review_comment.body }}"
