name: Docker Image CI

on:
  push:
    branches: [ "master" ]
 
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get PR Comment
        id: pr_comment
        uses: actions/github-script@v4
        with:
          script: |
            const pr_number = context.payload.pull_request.number;
            const comments = await github.pulls.listReviewComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr_number
            });
            const latest_comment = comments.data[comments.data.length - 1].body.trim();
            console.log(latest_comment);

      - name: Docker Login
        run: docker login -u airasuka -p ${{ secrets.DOCKER_HUB_PWD }}
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag airasuka/dockertest:${{ steps.pr_comment.outputs.comment }}
      - name: Push the Docker Image
        run: docker push airasuka/dockertest:${{ steps.pr_comment.outputs.comment }}
