name: Docker Image CI

on:
  push:
    branches: [ "brtest" ]
  pull_request:
    branches: [ "brtest" ]
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
    - name: Get a review comment
      id: PRcoment
      uses: actions/github-script@v4
      with:
        script: |
          const pr_number = context.payload.pull_request;
          console.log(pr_number);
    - name: Get print
      run: echo "${{ toJson(context) }}"
      # run: echo "${{ steps.PRcomment.outputs.pr_number }}"
   
